jpa:
  database: h2
  show-sql: false
  hibernate:
    ddl-auto: update
  properties:
    hibernate.format_sql: true
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    hibernate.cache.use_second_level_cache: false
    hibernate.search.default.directory_provider: filesystem
  h2:     #h2数据库远程管理
    console:
      enabled: true #开启web显示
      path: /db # 路径
      settings:
        web-allow-others: true
        trace: true #是否可以远程web

